### ISSUE TITLE
Please give documentation for this plugin. 

### ISSUE THREAD

**Issue by pranavkumar389** [ArunYogi/cordova-plugin-mosambee-pos#1]
Please give documentation for this plugin.

**Comment by Mahesh-Qpay** [comment]
Hello did you got document for mosambee plugin?

**Comment by pranavkumar389** [comment]
> Hello did you got document for mosambee plugin?

No.

**Comment by Mahesh-Qpay** [comment]
You implemented in cordova app?

**Comment by Mahesh-Qpay** [comment]
> > Hello did you got document for mosambee plugin?
> 
> No.

You implemented in cordova app? 
Can i get your guidance?

**Comment by pranavkumar389** [comment]
Sorry. That was a part of the research. I couldn't help you.

**Comment by Mahesh-Qpay** [comment]
> Sorry. That was a part of the research. I couldn't help you.

Ok @pranavkumar389
